### ISSUE TITLE
Generated theme.json incorrectly sets lineHeight values to number

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/create-block-theme#108] opened 2022-09-01 14:21 UTC
I noticed that when a theme.json is merged with site editor based data the lineHeight property is set to be a number when it should be a string. It doesn't seem to be happening with the core theme export.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1975950/187937520-a0e6b348-0c66-44b8-9fe7-b89442249209.png">

**Comment by t-hamano** [comment] 2024-01-07 09:05
Does this issue also occur with the latest Create Block Theme plugin? I tested the following steps, but could not reproduce it.

- Change and save line-height in the Global Styles
- Export the theme
- ✅ line-height is correctly enclosed in double quotes
- In the Create Block Theme menu, run "Overwrite Twenty Twenty-Four"
- Export the theme
- ✅ line-height is correctly enclosed in double quotes

**Comment by mikachan** [comment] 2024-01-08 08:29
Thanks for testing! I think this might've been an issue in Gutenberg that has since been fixed, so I think we can close this.

**Closed as completed by mikachan** 2024-01-08 08:29 UTC
Labels: bug
