### ISSUE TITLE
Several Missing Block Pattern Templates when Cloning Blockbase Theme

### ISSUE THREAD

**Issue by karks88** [WordPress/create-block-theme#79] opened 2022-07-06 16:40 UTC
I was experimenting with the plugin and making changes to the [Blockbase](https://wordpress.org/themes/blockbase/) theme. When I import the cloned theme into another local WordPress install, I get several errors regarding missing block pattern templates. For example:

> Warning: file_get_contents(www.mytestsite.dev.cc/wp-content/themes/cloneofblockbase/block-template-parts/header-centered.html): failed to open stream: No such file or directory in www.mytestsite.dev.cc\wp-content\themes\cloneofblockbase\inc\block-patterns.php on line 55

Exporting as a child theme seems to be a good workaround at this point.

**Comment by MaggieCabrera** [comment] 2022-07-11 08:39
Possible duplicate of https://github.com/WordPress/create-block-theme/issues/65

**Comment by pbking** [comment] 2024-04-29 13:14
Exporting Blockbase seems to work as expected (both as a clone and with child themes).  Including changing templates and patterns.  This appears to have been fixed at some point.  Closing as complete.  Please reopen if it continues to be a problem.

**Closed as completed by pbking** 2024-04-29 13:14 UTC
