### ISSUE TITLE
Zip File is corrupt when define( 'WP_DEBUG', true );

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#187] opened 2023-01-25 07:12 UTC
If you have your WP_DEBUG setting activated the resulting zip file is corrupted.

## How to reproduce
1. in your `wp-config.php` file look for WP_DEBUG setting and set it as true: `define( 'WP_DEBUG', true );`
2. Export a theme using the plugin
3. Try to open the exported zip file

**Comment by pax** [comment] 2023-02-27 12:15
Thanks for the observation. 
More specifically, `unzip` command outputs the following error:
> End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.

**Comment by philbraun** [comment] 2023-03-06 16:16
Interestingly, I just had the case when setting WP_DEBUG to false in wp-config.php only worked partially – most error messages (deprecations from PHP 8.1) were gone, but 4 remained stubbornly, and the zip file export failed (on MacOS).

Commenting out the WP_DEBUG line altogether fixed it.

**Comment by s-light** [comment] 2023-05-10 09:01
just run in exactly this issues!
for me it worked with `define('WP_DEBUG', false);`

**Comment by t-hamano** [comment] 2024-01-14 12:09
Does this error also occur in the latest version? I tested it in the following two environments, but could not reproduce it.

### 1 

- WordPress version: 6.4.2
- Plugin version: Latest (1.13.8)
- PHP version: 8.2.13
- Start local environment with wp-env
- Export Twenty Twenty-Four > I was able to unzip it using standard Windows functions.

### 2

- WordPress version: 6.4.2
- Plugin version: Latest (1.13.8)
- PHP version: 8.0.29
- Launch the site with [InstaWP](https://instawp.com/)
- Export Twenty Twenty-Four > I was able to unzip it using standard Windows functions.

**Comment by skorasaurus** [comment] 2024-04-11 16:15
not able to reproduce the error using the foloowing; 
WP 6.5.2 
2.0.2 of this plugin; 

able to unzip it successfully on ubuntu 20.04, using unzip.

**Comment by pbking** [comment] 2024-04-15 13:35
I also am unable to reproduce this.  Closing until it happens again.

**Closed as completed by pbking** 2024-04-15 13:35 UTC
