### ISSUE TITLE
In generated child theme the style.css of the parent isn't loaded.

### ISSUE THREAD

**Issue by seindal** [WordPress/create-block-theme#289] opened 2023-03-27 07:15 UTC
A child theme created with the plugin might not work as intended, ad the parent's style.css isn't loaded automatically.

In my case, to get it to work, I had to create a functions.php file in the new theme, with these lines:

`<?php

add_action( 'wp_enqueue_scripts', function () {
	$parenthandle = 'parent-style';
	$theme        = wp_get_theme();
	wp_enqueue_style( $parenthandle,
		get_template_directory_uri() . '/style.css',
		array(),  // If the parent theme code has a dependency, copy it to here.
		$theme->parent()->get( 'Version' )
	);
} );
`

Also, the id of the child's style.css in the generated HTML contains the name of the parent theme, not the child theme.

**Comment by matiasbenedetto** [comment] 2023-04-10 16:46
Hi @seindal :wave: , thanks for your report!

> parent's style.css isn't loaded automatically

I could not reproduce this issue.
What I did:
- Activated `Disco` theme.
- Created a child theme
- Activated child theme created

Result: Disco (parent theme) `styles.css` file is loading fine in the child theme. 



Please note that [Disco enqueues its own `style.css` file using `functions.php`](https://github.com/Automattic/themes/blob/970f13486a1aa8864201be8a0703c636198a7238/disco/functions.php#L34-L60). If the theme you are using as the parent theme is not enqueuing their own `style.css` file, it won't load on the child theme either. For example, Twenty Twenty-Three doesn't load any theme CSS file. This is how WordPress works and it's not specifically related to the plugin.

> The id of the child's style.css in the generated HTML contains the name of the parent theme, not the child theme.

This issue was [already fixed here](https://github.com/WordPress/create-block-theme/pull/301) and released as part of the 1.8.1 version of the plugin. Related to the answer above: If your parent theme was enqueuing the `style.css` file this name collision between parent and child could be causing the problem. Please update the plugin version and try again.


I'm closing this issue but feel free to re-open it if your problem persists!

**Closed as completed by matiasbenedetto** 2023-04-10 16:46 UTC
