### ISSUE TITLE
[Safari browser] Local font upload not working as expected 

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#302] opened 2023-04-04 15:48 UTC
Local font upload not working as expected on Safari browser:

In the video, we can see that the font metadata is not being read and completed in the form. If the form is completed manually the submit button is still disabled. Chrome, Firefox, and Gnome Browser are working as expected.

Thanks, @beafialho for reporting this and recording the screencast.

https://user-images.githubusercontent.com/1310626/229846011-aef8460e-d462-4d5c-931f-80af75237bd7.mp4

**Comment by vcanales** [comment] 2023-04-04 17:19
I could not reproduce this issue on Safari `Version 16.3 (18614.4.6.1.6)`, on an M1 MacBook Pro. Uploading the same font used by @beafialho in the video didn't help; the font is previewed, and the form is auto-filled correctly.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/1157901/229868827-bc6232f8-ce66-4427-b39e-32e026c811ac.png">

**Comment by jeffikus** [comment] 2023-04-04 19:05
I tested this with Version 16.3 (18614.4.6.1.5) on m1 Macbook Pro without issue. I tested with multiple .ttf fonts including the Commissioner-LightItalic.otf font in the video.

@beafialho what hardware are you running this on?

**Comment by beafialho** [comment] 2023-04-05 09:19
> @beafialho what hardware are you running this on?

An M1 iMac and the Safari Version is 16.2 (18614.3.7.1.5).

**Comment by mikachan** [comment] 2023-04-05 10:09
Just to add another version to the mix - I also couldn't reproduce this, and I was using Safari Version 16.1 (18614.2.9.1.12). So perhaps this is a bug specific to 16.2?

**Comment by t-hamano** [comment] 2024-04-29 15:31
Since this feature has been integrated into the native font library, can this issue be closed?

**Comment by pbking** [comment] 2024-04-30 11:53
Yup.  Closing.

**Closed as completed by pbking** 2024-04-30 11:53 UTC
