### ISSUE TITLE
Image/assets are lost while exporting theme with CBT plugin

### ISSUE THREAD

**Issue by henriqueiamarino** [WordPress/create-block-theme#516] opened 2024-03-08 10:48 UTC
Themes created with the Create Block Theme plugin do not show their images once installed. I use one theme here as an example, but the issue is recurrent in all I have created lately.

[dada.zip](https://github.com/WordPress/create-block-theme/files/14537060/dada.zip)

As mentioned, the background image is broken — like all others. Even if the designer adds them manually to the assets folder as I did to the example, they still not show.

<img width="1620" alt="Screenshot 2024-03-08 at 11 44 34" src="https://github.com/WordPress/create-block-theme/assets/103748085/d9526849-928b-4cd7-89f6-a2ffa2ad9ff9">

**Comment by pbking** [comment] 2024-03-08 16:11
This may be a duplicate of #336

**Comment by pbking** [comment] 2024-03-27 13:44
This should be fixed with #522

**Closed as completed by pbking** 2024-03-27 13:44 UTC
Labels: bug
