### ISSUE TITLE
Editor font resets to serif

### ISSUE THREAD

**Issue by jenxi** [WordPress/create-block-theme#412] opened 2023-07-10 11:01 UTC
There seems to be conflict with SEO plugins that is causing the custom font to in the editor to reset to “serif". Disabling the SEO plugin resolves the issue. This happens with Rank Math SEO, SEO Press and All-in-One SEO.

The font displays correctly on the published page and in the site editor. It is only the page/post editor that is having issues.

For example, on a site with custom font set to Open Sans, these are the CSS snippets applying `font-family`.

posts.php
```
.editor-styles-wrapper {
  font-family: var(--wp--preset--font-family--open-sans);
} 
```

reset.css
```
html :where(.editor-styles-wrapper) {
  font-family: serif;
}
```

Computed style is shows `font-family` as Open Sans but the editor shows serif instead.

**Comment by jenxi** [comment] 2023-07-13 04:41
Enabling these plugins also caused the issue:

Head, Footer and Post Injections
WPCode Lite

**Comment by t-hamano** [comment] 2024-01-07 09:55
I tested using Twenty Twent-Four, but could not reproduce it.

In TT4, the base font family is Inter:

![image](https://github.com/WordPress/create-block-theme/assets/54422211/48b84999-2770-43e2-a776-8646fab73a0a)

After installing Rank Math SEO plugin, open the Post Editor. The Paragraph block font is Inter:

![image](https://github.com/WordPress/create-block-theme/assets/54422211/49a4f436-8935-4190-bd63-d7d6de48465a)

**Comment by pbking** [comment] 2024-04-29 12:43
Unable to reproduce and font management happens (mostly) in core.  The issues doesn't seem to be relevant any more; closing.

**Closed as completed by pbking** 2024-04-29 12:43 UTC
