### ISSUE TITLE
Error: "Template part has been deleted or unavailable:header".

### ISSUE THREAD

**Issue by ashrudral** [WordPress/create-block-theme#429] opened 2023-07-28 11:59 UTC
I am still getting the issue of "Template part has been deleted or unavailable:header". 
Objective: create child theme of blockbase and spectra.

Wordpress: I am on WP 6.2
create block theme version 1.13.1. 
<img width="960" alt="Screenshot 2023-07-28 163829" src="https://github.com/WordPress/create-block-theme/assets/73318936/f2a1f80a-5253-4897-8fc1-0086babfbb08">

How to recreate the error:
1. Install blockbase theme on fresh WP site version 6.2.2
2. Install create block theme plugin
3. create child them with only 1 word name for child theme.
4. download child zip
5. upload child theme zip 
6. activate theme
7. Go to site, following error:
"Template part has been deleted or unavailable:header". 
"Template part has been deleted or unavailable:footer". 
This error is there in many more places such as icons meta, post meta, etc.

**Comment by bystrzan** [comment] 2023-08-27 16:12
There's a problem with handling the template parts - You can easly fix it by adding to the frontpage.html "theme name / slug", so get header part will look like: 

`<!-- wp:template-part {"slug":"header","theme":"YOUR_THEME_SLUG","tagName":"header"} /-->`

Ofcourse you should update it also in DB by switch to show code and replace exported - buggy version of those lines.

Same for any other template part. I found that this problem isn't always the problem with Create Theme Plugin, but mostly when theme has a name where 2 or more words, or / and template part has own pattern inside.

The above fix is quickfix / hotfix for developers that already creating the themes with this plugin.

**Comment by ashrudral** [comment] 2023-08-27 17:47
Just want to mention again that:
1) I am using single word name. My child theme name: "Blockbasechild"
2) The parent theme is Blockbase.

Thank you for your response. Indeed, It must be a pattern inside the parent theme causing error. The quick fox you provided, I don't fully understand where to insert that snippet? 

Luckily, I was able to manually create a child theme by creating a style.css and function.php file in the child theme folder and it is working for me.

**Comment by bystrzan** [comment] 2023-08-28 10:30
@ashrudral
1. So this is not a problem (theme name / slug)
2. It doesn't matter what theme it is - the problem is that while exporting changes from DB to the theme frontpage.html the CBT plugin often miss some part of code that should be included to get global template parts to work.
3. Steps to fix the problem (each time you export or save changes to the theme files):
- A) Go to edit your Front Page in Editor and in the top right corner click 3 dots menu and click on "Code Editor".
- B) Open frontpage.html in code editor on your computer and:
- for A & B replace first and last lines - like here:

**this:** 
`<!-- wp:template-part {"slug":"header","tagName":"header"} /-->`
**with: ↓**
`<!-- wp:template-part {"slug":"header","theme":"blockbasechild","area":"header"} /-->`

**and this:** 
`<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->`
**with: ↓**
`<!-- wp:template-part {"slug":"footer","theme":"blockbasechild","area":"footer"} /-->`


You can read more about this bug here:
- https://github.com/WordPress/create-block-theme/issues/448
- https://github.com/WordPress/create-block-theme/issues/275
- https://github.com/WordPress/create-block-theme/issues/396

**Comment by pbking** [comment] 2023-09-20 02:08
This is the issue to watch.  Rendering a template-part from a pattern doesn't work as it should unless you include the theme attribute, however including the theme attribute means that the theme HAS to be installed at the "top level" of the /theme folder which isn't always the case.  Thus rendering correctly without the theme attribute is the fix to make.  In the meantime I suggest avoid using template parts in patterns.

https://github.com/WordPress/gutenberg/issues/53194

**Comment by t-hamano** [comment] 2024-01-07 09:44
Now that https://github.com/WordPress/gutenberg/pull/54595 has been merged, can we close this issue?

**Comment by mikachan** [comment] 2024-01-08 08:30
> Now that https://github.com/WordPress/gutenberg/pull/54595 has been merged, can we close this issue?

Yes, I think so! 🎉

**Closed as completed by mikachan** 2024-01-08 08:30 UTC
