### ISSUE TITLE
Downloads empty zip file

### ISSUE THREAD

**Issue by troytempleman** [WordPress/create-block-theme#20] opened 2021-11-20 00:44 UTC
Hi,

When I go to Appearance > Create Blockbase Theme, fill in the fields and click the Create Blockbase Theme button, it downloads a .zip file succesfully, but the file is 0 bytes. When I try to unzip it, I get a .zip.cpgz file, which I'm unable to open.

I have the following installed:

WordPress 5.82
Blockbase 1.4.3
Gutenberg 11.9.0
(no other plugins)

Thanks,
Troy

**Comment by scruffian** [comment] 2021-11-20 22:38
Do you have the blockbase theme installed and active?

**Comment by troytempleman** [comment] 2021-11-21 00:11
@scruffian yes, Blockbase theme is installed and active. 

I notice the same happens when I attempt to download templates in Appearance > Editor > More tools & options > Export.

Will also test in different environment and report back.

**Comment by troytempleman** [comment] 2021-11-21 19:19
Both work perfectly locally. 

Issue was with LAMP web server with PHP 7.3.30.

**Comment by scruffian** [comment] 2021-11-21 22:48
Thanks, I'll investigate further

**Comment by scruffian** [comment] 2021-11-22 09:55
Do you get any errors in your console, or in the server error_log?

**Comment by troytempleman** [comment] 2021-11-25 00:30
@scruffian no console errors on the Appearance > Create Blockbase Theme page, but I see the following several times in error_log:

`PHP Fatal error:  Uncaught Error: Call to undefined function gutenberg_block_template_part() in /home/bkrdhbhau469/public_html/test2/wp-content/themes/blockbase/header.php:16
Stack trace:
#0 /home/bkrdhbhau469/public_html/test2/wp-includes/template.php(770): require_once()
#1 /home/bkrdhbhau469/public_html/test2/wp-includes/template.php(716): load_template('/home/bkrdhbhau...', true, Array)
#2 /home/bkrdhbhau469/public_html/test2/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#3 /home/bkrdhbhau469/public_html/test2/wp-content/themes/blockbase/404.php(8): get_header()
#4 /home/bkrdhbhau469/public_html/test2/wp-includes/template-loader.php(106): include('/home/bkrdhbhau...')
#5 /home/bkrdhbhau469/public_html/test2/wp-blog-header.php(19): require_once('/home/bkrdhbhau...')
#6 /home/bkrdhbhau469/public_html/test2/index.php(17): require('/home/bkrdhbhau...')
#7 {main}
  thrown in /home/bkrdhbhau469/public_html/test2/wp-content/themes/blockbase/header.php on line 16`

**Comment by MaggieCabrera** [comment] 2021-11-25 08:25
@troytempleman can you try again with the latest version of Blockbase? it's now at v 2.0.0, get GB v12.0.0 as well or you'll run into a different fatal :D

**Comment by tinjure20** [comment] 2021-11-25 19:45
I can't create theme as well under my local environment (WordPress: 5.8.2; Gutenberg: 12.0.1; Blockbase: 2.0.0; Create Blockbase theme plugin from trunk - downloaded today). 

Screenshot:
![Error-Screenshot](https://user-images.githubusercontent.com/59660253/143494000-363fe1ef-8851-49f7-a887-d84ad95ab88f.png)

I didn't get any email in my account associate-email box. 

PHP erro_log:
`[25-Nov-2021 19:19:09 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function _remove_theme_attribute_in_block_template_content() in /Users/Tinjure/Documents/sites/twenty-two/wp-content/plugins/create-blockbase-theme-trunk/index.php:194
Stack trace:
#0 /Users/Tinjure/Documents/sites/twenty-two/wp-content/plugins/create-blockbase-theme-trunk/index.php(268): gutenberg_edit_site_export_theme_create_zip('/private/var/fo...', Array)
#1 /Users/Tinjure/Documents/sites/twenty-two/wp-content/plugins/create-blockbase-theme-trunk/index.php(342): gutenberg_edit_site_export_theme(Array)
#2 /Users/Tinjure/Documents/sites/twenty-two/wp-includes/class-wp-hook.php(303): blockbase_save_theme('')
#3 /Users/Tinjure/Documents/sites/twenty-two/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#4 /Users/Tinjure/Documents/sites/twenty-two/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /Users/Tinjure/Documents/sites/twenty-two/wp-admin/admin.php(175): do_action('admin_init')
#6 /Users/Tinjure/Documents/sites/twenty-two/wp-admin/themes. in /Users/Tinjure/Documents/sites/twenty-two/wp-content/plugins/create-blockbase-theme-trunk/index.php on line 194`

**Comment by scruffian** [comment] 2021-11-25 22:25
I think `_remove_theme_attribute_in_block_template_content` didn't make it into the latest version of Gutenberg yet. There's two way around this. Either you can revert the change that was merged in https://github.com/Automattic/create-blockbase-theme/pull/19, or you can run the `trunk` version of Gutenberg. Sorry about the confusion. Hopefully things will become more stable soon.

**Comment by troytempleman** [comment] 2021-11-25 23:36
@MaggieCabrera same result with trunk of Gutenburg, Blockbase and this plugin :/

**Comment by scruffian** [comment] 2021-11-26 13:43
In https://github.com/Automattic/create-blockbase-theme/pull/24 we made a change so it should work with trunk or v12...

**Comment by tinjure20** [comment] 2021-11-26 18:22
Yep, with the latest changes it just works fine as expected. Thank you

**Comment by scruffian** [comment] 2021-12-10 11:43
Please reopen if this is still not working.

**Comment by MaggieCabrera** [comment] 2022-07-04 16:13
Can we close this? I can't reproduce

**Comment by scruffian** [comment] 2022-07-04 18:03
I think it was left open in error.

**Closed as completed by scruffian** 2022-07-04 18:03 UTC
